version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  
  build:
    commands:
      - cd API
      - npm install
      - npm run build
      - echo $PACKAGE_BUCKETNAME
      - echo $PACKAGE_FOLDER
      - |
        sam package \
          --template-file template.yaml \
          --output-template-file packaged.yaml \
          --s3-bucket $PACKAGE_BUCKETNAME \
          --s3-prefix $PACKAGE_FOLDER

artifacts:
  base-directory: ./API/lib
  files:
    - '**/*'    

cache:
  paths:
    - './node_modules/**/*'
