version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  
  build:
    commands:
      - echo starting build...
      - echo $S3_BUCKETNAME
      - echo $S3_FOLDER
      - cd API
      - npm install
      - npm run build
      - cd lib
      - |
        sam package \
          --template-file template.yaml \
          --output-template-file packaged.yaml \
          --s3-bucket $S3_BUCKETNAME \
          --s3-prefix $S3_FOLDER

artifacts:
  base-directory: ./API/lib
  files:
    - '**/*'    

cache:
  paths:
    - './node_modules/**/*'
