version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  
  build:
    commands:
      - echo starting build...
      - echo $PACKAGE_BUCKETNAME
      - echo $PACKAGE_FOLDER
      - echo $STACK_NAME
      - echo $TABLE_NAME
      - echo $STAGE_NAME
      - |
        sam package \
          --template-file template.yaml \
          --output-template-file packaged.yaml \
          --s3-bucket $PACKAGE_BUCKETNAME \
          --s3-prefix $PACKAGE_FOLDER
      - |
        sam deploy \
          --template-file packaged.yaml \
          --stack-name $STACK_NAME \
          --capabilities CAPABILITY_IAM \        
          --parameter-overrides TableName=$TABLE_NAME StageName=$STAGE_NAME

cache:
  paths:
    - './node_modules/**/*'
