version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - cd ui
      - npm run build
      - cd ../

artifacts:
  base-directory: ./ui/build
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'
