version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  
  pre_build:
    commands:
      - cd ./ui

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - cd ./

artifacts:
  base-directory: ./ui/build
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'
