version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  
  build:
    commands:
      - cd UI
      - npm install
      - npm run build

artifacts:
  base-directory: ./UI/build
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'
